### impor libarys

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
import matplotlib.pyplot as plt

### load dataset

In [2]:
data_path = Path("../data/Palo Alto Networks.csv")
df1 = pd.read_csv(data_path)

In [3]:
df = df1

In [4]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,Female,...,3,1,0,8,0,1,6,4,0,5
1,49,0,Travel_Frequently,279,Research & Development,8,1,Life Sciences,3,Male,...,4,4,1,10,3,3,10,7,1,7
2,37,1,Travel_Rarely,1373,Research & Development,2,2,Other,4,Male,...,3,2,0,7,3,3,0,0,0,0
3,33,0,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,4,Female,...,3,3,0,8,3,3,8,7,3,0
4,27,0,Travel_Rarely,591,Research & Development,2,1,Medical,1,Male,...,3,4,1,6,3,3,2,2,2,2

### dataset shape

In [6]:
print(f"dataset shape",df.shape)
print(f"number of row",df.shape[0])
print(f"number of columns",df.shape[1])

dataset shape (1470, 31)
number of row 1470
number of columns 31

### columns names

In [8]:
print("Dataset Columns:\n")

for i, col in enumerate(df.columns, start=1):
    print(f"{i}. {col}")

Dataset Columns:

1. Age
2. Attrition
3. BusinessTravel
4. DailyRate
5. Department
6. DistanceFromHome
7. Education
8. EducationField
9. EnvironmentSatisfaction
10. Gender
11. HourlyRate
12. JobInvolvement
13. JobLevel
14. JobRole
15. JobSatisfaction
16. MaritalStatus
17. MonthlyIncome
18. MonthlyRate
19. NumCompaniesWorked
20. OverTime
21. PercentSalaryHike
22. PerformanceRating
23. RelationshipSatisfaction
24. StockOptionLevel
25. TotalWorkingYears
26. TrainingTimesLastYear
27. WorkLifeBalance
28. YearsAtCompany
29. YearsInCurrentRole
30. YearsSinceLastPromotion
31. YearsWithCurrManager

### columns datatypes

In [7]:
dtype_summary = pd.DataFrame({
    'Column': df.columns,
    'Data_Type': df.dtypes.values
})

display(dtype_summary)

                      Column Data_Type
0                        Age     int64
1                  Attrition     int64
2             BusinessTravel    object
3                  DailyRate     int64
4                 Department    object
5           DistanceFromHome     int64
6                  Education     int64
7             EducationField    object
8    EnvironmentSatisfaction     int64
9                     Gender    object
10                HourlyRate     int64
11            JobInvolvement     int64
12                  JobLevel     int64
13                   JobRole    object
14           JobSatisfaction     int64
15             MaritalStatus    object
16             MonthlyIncome     int64
17               MonthlyRate     int64
18        NumCompaniesWorked     int64
19                  OverTime    object
20         PercentSalaryHike     int64
21         PerformanceRating     int64
22  RelationshipSatisfaction     int64
23          StockOptionLevel     int64
24         TotalWorkingYears     int64
25     TrainingTimesLastYear     int64
26           WorkLifeBalance     int64
27            YearsAtCompany     int64
28        YearsInCurrentRole     int64
29   YearsSinceLastPromotion     int64
30      YearsWithCurrManager     int64

### info about dataset

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 31 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   int64
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EnvironmentSatisfaction   1470 non-null   int64
 9   Gender                    1470 non-null   object
 10  HourlyRate                1470 non-null   int64
 11  JobInvolvement            1470 non-null   int64
 12  JobLevel                  1470 non-null   int64
 13  JobRole                   1470 non-null   object
 14  JobSatisfaction           1470 non-null   int64
 15  MaritalStatus             1470 non-null   object
 16  MonthlyIncome             1470 non-null   int64
 17  MonthlyRate               1470 non-null   int64
 18  NumCompaniesWorked        1470 non-null   int64
 19  OverTime                  1470 non-null   object
 20  PercentSalaryHike         1470 non-null   int64
 21  PerformanceRating         1470 non-null   int64
 22  RelationshipSatisfaction  1470 non-null   int64
 23  StockOptionLevel          1470 non-null   int64
 24  TotalWorkingYears         1470 non-null   int64
 25  TrainingTimesLastYear     1470 non-null   int64
 26  WorkLifeBalance           1470 non-null   int64
 27  YearsAtCompany            1470 non-null   int64
 28  YearsInCurrentRole        1470 non-null   int64
 29  YearsSinceLastPromotion   1470 non-null   int64
 30  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(24), object(7)
memory usage: 356.1+ KB

### first 5 rcords

In [10]:
display(df.head())

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,Female,...,3,1,0,8,0,1,6,4,0,5
1,49,0,Travel_Frequently,279,Research & Development,8,1,Life Sciences,3,Male,...,4,4,1,10,3,3,10,7,1,7
2,37,1,Travel_Rarely,1373,Research & Development,2,2,Other,4,Male,...,3,2,0,7,3,3,0,0,0,0
3,33,0,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,4,Female,...,3,3,0,8,3,3,8,7,3,0
4,27,0,Travel_Rarely,591,Research & Development,2,1,Medical,1,Male,...,3,4,1,6,3,3,2,2,2,2

### Numerical Statistical Summary

In [11]:
df.describe()

,Age,Attrition,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,...,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,0.161224,802.485714,9.192517,2.912925,2.721769,65.891156,2.729932,2.063946,2.728571,...,3.153741,2.712245,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,0.367863,403.509100,8.106864,1.024165,1.093082,20.329428,0.711561,1.106940,1.102846,...,0.360824,1.081209,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,0.000000,102.000000,1.000000,1.000000,1.000000,30.000000,1.000000,1.000000,1.000000,...,3.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,0.000000,465.000000,2.000000,2.000000,2.000000,48.000000,2.000000,1.000000,2.000000,...,3.000000,2.000000,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,0.000000,802.000000,7.000000,3.000000,3.000000,66.000000,3.000000,2.000000,3.000000,...,3.000000,3.000000,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,0.000000,1157.000000,14.000000,4.000000,4.000000,83.750000,3.000000,3.000000,4.000000,...,3.000000,4.000000,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1.000000,1499.000000,29.000000,5.000000,4.000000,100.000000,4.000000,5.000000,4.000000,...,4.000000,4.000000,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

### Categorical Summary

In [12]:
display(df.describe(include='object'))

,BusinessTravel,Department,EducationField,Gender,JobRole,MaritalStatus,OverTime
count,1470,1470,1470,1470,1470,1470,1470
unique,3,3,6,2,9,3,2
top,Travel_Rarely,Research & Development,Life Sciences,Male,Sales Executive,Married,No
freq,1043,961,606,882,326,673,1054

In [13]:
# ==========================================
# DAY 3 - DATASET OVERVIEW SUMMARY
# ==========================================

dataset_overview = pd.DataFrame({
    'Metric': [
        'Number of Records',
        'Number of Columns',
        'Missing Values',
        'Duplicate Rows',
        'Numerical Columns',
        'Categorical Columns'
    ],
    
    'Value': [
        df.shape[0],
        df.shape[1],
        df.isnull().sum().sum(),
        df.duplicated().sum(),
        df.select_dtypes(include=['int64', 'float64']).shape[1],
        df.select_dtypes(include=['object']).shape[1]
    ]
})

display(dataset_overview)

                Metric  Value
0    Number of Records   1470
1    Number of Columns     31
2       Missing Values      0
3       Duplicate Rows      0
4    Numerical Columns     24
5  Categorical Columns      7